/**
 * API Configuration
 * Centralized API endpoint and configuration management
 */

export const API_CONFIG = {
  // Base URL - Change based on environment
  BASE_URL: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8080/api',
  
  // Timeout in milliseconds
  TIMEOUT: 30000,
  
  // API Endpoints organized by module
  ENDPOINTS: {
    // ===== AUTHENTICATION =====
    AUTH: {
      SEND_REGISTRATION_OTP: '/auth/send-registration-otp',
      REGISTER: '/auth/register',
      VENDOR_REGISTER: '/auth/vendor/register',
      ADMIN_REGISTER: '/auth/admin/register',
      SUPPORT_REGISTER: '/auth/support/register',
      CTO_REGISTER: '/auth/cto/register',
      DATA_ENTRY_REGISTER: '/auth/data-entry/register',
      LOGIN: '/auth/login',
      BUYER_LOGIN: '/auth/buyer/login',
      SELLER_LOGIN: '/auth/seller/login',
      ADMIN_LOGIN: '/auth/admin/login',
      SUPPORT_LOGIN: '/auth/support/login',
      CTO_LOGIN: '/auth/cto/login',
      DATA_ENTRY_LOGIN: '/auth/data-entry/login',
      LOGIN_OTP: '/auth/login-otp',
      VERIFY_OTP: '/auth/verify-otp',
      FORGOT_PASSWORD: '/auth/forgot-password',
      VERIFY_FORGOT_PASSWORD_OTP: '/auth/verify-forgot-password-otp',
      CHANGE_PASSWORD: '/auth/change-password',
      GET_PROFILE: '/auth/profile',
      UPDATE_PROFILE: '/auth/profile',
      CHECK_EMAIL_ROLE: '/auth/check-email-role',
    },

    // ===== USER MANAGEMENT =====
    USERS: {
      GET_ALL_USERS: '/users',
      GET_USERS_BY_ROLE: (role: string) => `/users/role/${role}`,
      GET_USER_BY_ID: (id: number) => `/users/${id}`,
      GET_USER_BY_EMAIL: (email: string) => `/users/email/${email}`,
      GET_USER_BY_PHONE: (phone: string) => `/users/phone/${phone}`,
      GET_VERIFIED_USERS: '/users/verified',
      GET_UNVERIFIED_USERS: '/users/unverified',
      GET_ACTIVE_USERS: '/users/active',
      GET_INACTIVE_USERS: '/users/inactive',
      UPDATE_USER: (id: number) => `/users/${id}`,
      DELETE_USER: (id: number) => `/users/${id}`,
      ACTIVATE_USER: (id: number) => `/users/${id}/activate`,
      DEACTIVATE_USER: (id: number) => `/users/${id}/deactivate`,
      GET_USER_COUNT: '/users/count',
      GET_USER_COUNT_BY_ROLE: (role: string) => `/users/count/role/${role}`,
      CHECK_EMAIL_EXISTS: (email: string) => `/users/exists/email/${email}`,
      CHECK_PHONE_EXISTS: (phone: string) => `/users/exists/phone/${phone}`,
      GET_REGULAR_USERS: '/users/regular',
    },

    // ===== PRODUCTS =====
    PRODUCTS: {
      GET_ALL_PRODUCTS: '/products',
      GET_PRODUCT_BY_ID: (id: number) => `/products/${id}`,
      SEARCH_PRODUCTS: '/products/search',
      GET_SEARCH_SUGGESTIONS: '/products/search/suggestions',
      GET_PRODUCTS_BY_CATEGORY: (categoryId: number) => `/products/category/${categoryId}`,
      GET_PRODUCTS_BY_VENDOR: (vendorId: number) => `/products/vendor/${vendorId}`,
      GET_FEATURED_PRODUCTS: '/products/featured',
      GET_FILTERED_PRODUCTS: '/products/categories',
      ADD_PRODUCT: '/products',
      ADD_PRODUCT_VENDOR: '/products/vendor/add',
      UPLOAD_PRODUCT_IMAGES: (id: number) => `/products/${id}/images`,
      UPDATE_PRODUCT_IMAGES: (id: number) => `/products/${id}/images`,
      UPDATE_PRODUCT: (id: number) => `/products/${id}`,
      DELETE_PRODUCT: (id: number) => `/products/${id}`,
      GET_VENDOR_PRODUCTS: '/products/vendor/my-products',
      GET_VENDOR_PRODUCTS_TEST: (vendorId: number) => `/products/test/vendor/${vendorId}/products`,
      GET_VENDOR1_PRODUCTS: '/products/vendor1/products',
      UPDATE_PRODUCT_STATUS: (id: number) => `/products/${id}/status`,
      APPROVE_PRODUCT: (id: number) => `/products/${id}/approve`,
      FEATURE_PRODUCT: (id: number) => `/products/${id}/feature`,
      GET_PENDING_APPROVAL_PRODUCTS: '/products/pending-approval',
      DATA_ENTRY_ADD_PRODUCT: '/products/data-entry',
    },

    // ===== CART =====
    CART: {
      GET_CART: '/cart',
      GET_CART_ITEMS: '/cart/items',
      ADD_TO_CART: '/cart/add',
      ADD_MULTIPLE_TO_CART: '/cart/add-multiple',
      UPDATE_CART_ITEM: (itemId: number) => `/cart/item/${itemId}`,
      UPDATE_QUANTITY: (itemId: number) => `/cart/item/${itemId}/quantity`,
      REMOVE_FROM_CART: (itemId: number) => `/cart/item/${itemId}`,
      REMOVE_MULTIPLE_FROM_CART: '/cart/remove-multiple',
      CLEAR_CART: '/cart/clear',
      GET_CART_COUNT: '/cart/count',
      GET_CART_TOTAL: '/cart/total',
      APPLY_COUPON: '/cart/apply-coupon',
      REMOVE_COUPON: '/cart/remove-coupon',
      VALIDATE_CART: '/cart/validate',
      SAVE_FOR_LATER: (itemId: number) => `/cart/item/${itemId}/save-for-later`,
      GET_SAVED_ITEMS: '/cart/saved-items',
      MOVE_TO_CART: (itemId: number) => `/cart/saved-items/${itemId}/move-to-cart`,
      REMOVE_SAVED_ITEM: (itemId: number) => `/cart/saved-items/${itemId}`,
      GET_CART_SUMMARY: '/cart/summary',
      CALCULATE_TAX: '/cart/calculate-tax',
      CALCULATE_SHIPPING: '/cart/calculate-shipping',
      PROCEED_TO_CHECKOUT: '/cart/checkout',
      VALIDATE_BEFORE_CHECKOUT: '/cart/validate-checkout',
    },

    // ===== ORDERS =====
    ORDERS: {
      CREATE_ORDER: '/orders',
      UPDATE_ORDER: (id: number) => `/orders/${id}`,
      DELETE_ORDER: (id: number) => `/orders/${id}`,
      GET_ALL_ORDERS: '/orders',
      GET_USER_ORDERS: (userId: number) => `/orders/user/${userId}`,
      FILTER_ORDERS: '/orders/filter',
      SEARCH_ORDERS: '/orders/search',
      GET_BY_STATUS: (status: string) => `/orders/status/${status}`,
      UPDATE_STATUS: (id: number) => `/orders/${id}/status`,
      CANCEL_ORDER: (id: number) => `/orders/${id}/cancel`,
      COMPLETE_ORDER: (id: number) => `/orders/${id}/complete`,
      SHIP_ORDER: (id: number) => `/orders/${id}/ship`,
      UPDATE_PAYMENT_STATUS: (id: number) => `/orders/${id}/payment-status`,
      GET_PAYMENT_DETAILS: (id: number) => `/orders/${id}/payment`,
      REFUND_ORDER: (id: number) => `/orders/${id}/refund`,
      TRACK_ORDER: (orderNumber: string) => `/orders/track/${orderNumber}`,
      GET_TRACKING_DETAILS: (id: number) => `/orders/${id}/tracking`,
      GET_STATISTICS: '/orders/statistics',
      GET_TOTAL_COUNT: '/orders/count',
      GET_TOTAL_REVENUE: '/orders/revenue',
      GET_REVENUE_BY_DATE: '/orders/revenue/by-date',
      GET_PENDING_ORDERS: '/orders/pending',
      GET_RECENT_ORDERS: '/orders/recent',
      GET_BY_DATE_RANGE: '/orders/date-range',
      EXPORT_ORDERS: '/orders/export',
      CHECKOUT: '/orders/checkout',
      VERIFY_PAYMENT: '/orders/verify-payment',
      GET_MY_ORDERS: '/orders/my-orders',
      GET_MY_ORDERS_PAGINATED: '/orders/my-orders/paginated',
      GET_ORDER_BY_ID: (id: number) => `/orders/${id}`,
      GET_ORDER_BY_NUMBER: (orderNumber: string) => `/orders/number/${orderNumber}`,
      UPDATE_ORDER_STATUS: (id: number) => `/orders/${id}/status`,
      GET_VENDOR_ORDERS: '/orders/vendor/my-orders',
      GET_VENDOR_ORDERS_PAGINATED: '/orders/vendor/my-orders/paginated',
    },

    // ===== BUYER LEADS =====
    BUYER_LEADS: {
      CREATE_LEAD: '/buyer-leads',
      GET_LEADS_FOR_SALES: '/buyer-leads/sales',
      GET_LEAD_BY_ID: (id: number) => `/buyer-leads/${id}`,
      UPDATE_LEAD_STATUS: (id: number) => `/buyer-leads/${id}/status`,
      ASSIGN_LEAD: (id: number) => `/buyer-leads/${id}/assign`,
      GET_HIGH_PRIORITY_LEADS: '/buyer-leads/high-priority',
      GET_LEADS_NEEDING_FOLLOWUP: '/buyer-leads/follow-up',
      GET_LEADS_BY_SALES_REP: (rep: string) => `/buyer-leads/sales-rep/${rep}`,
      GET_LEAD_STATS: '/buyer-leads/stats',
      GET_CONVERSION_ANALYTICS: '/buyer-leads/analytics/conversion',
      GET_SOURCES_ANALYTICS: '/buyer-leads/analytics/sources',
      GET_LEAD_FUNNEL: '/buyer-leads/funnel',
      GET_SIMILAR_LEADS: (id: number) => `/buyer-leads/${id}/similar`,
      EXPORT_LEADS: '/buyer-leads/export',
      GET_LEAD_TIMELINE: (id: number) => `/buyer-leads/${id}/timeline`,
      UPDATE_LEAD_SCORE: (id: number) => `/buyer-leads/${id}/score`,
      BULK_UPDATE_LEADS: '/buyer-leads/bulk-update',
      DELETE_LEAD: (id: number) => `/buyer-leads/${id}`,
      ADD_INTERACTION: (id: number) => `/buyer-leads/${id}/interactions`,
      GET_LEADS_BY_CATEGORY: (category: string) => `/buyer-leads/category/${category}`,
      GET_LEADS_BY_PRICE_RANGE: '/buyer-leads/price-range',
      GET_STALE_LEADS: '/buyer-leads/stale',
      GET_DASHBOARD_METRICS: '/buyer-leads/dashboard-metrics',
    },

    // ===== INQUIRIES =====
    INQUIRIES: {
      CREATE_INQUIRY: '/inquiries',
      CREATE_INQUIRY_DIRECT: '/inquiries/direct',
      GET_ALL_INQUIRIES: '/inquiries',
      GET_MY_INQUIRIES: '/inquiries/my-inquiries',
      GET_VENDOR_INQUIRIES: '/inquiries/vendor-inquiries',
      GET_VENDOR_UNRESOLVED: '/inquiries/vendor-unresolved',
      MARK_RESOLVED: (id: number) => `/inquiries/${id}/resolve`,
      GET_PRODUCT_INQUIRIES: (productId: number) => `/inquiries/product/${productId}`,
    },

    // ===== QUOTES =====
    QUOTES: {
      CREATE_QUOTE: '/quotes',
      GET_ALL_QUOTES: '/quotes',
      GET_MY_QUOTES: '/quotes/my-quotes',
      GET_MY_RECEIVED_QUOTES: '/quotes/my-received-quotes',
      ACCEPT_QUOTE: (id: number) => `/quotes/${id}/accept`,
    },

    // ===== REVIEWS =====
    REVIEWS: {
      CREATE_REVIEW: '/reviews',
      GET_REVIEW_BY_ID: (id: number) => `/reviews/${id}`,
      UPDATE_REVIEW: (id: number) => `/reviews/${id}`,
      DELETE_REVIEW: (id: number) => `/reviews/${id}`,
      GET_MY_REVIEWS: '/reviews/my-reviews',
      GET_ALL_REVIEWS: '/reviews',
      GET_BY_RATING: (productId: number, rating: number) => `/reviews/product/${productId}/rating/${rating}`,
      GET_BY_USER: (userId: number) => `/reviews/user/${userId}`,
      GET_AVERAGE_RATING: (productId: number) => `/reviews/product/${productId}/average`,
      GET_RATING_DISTRIBUTION: (productId: number) => `/reviews/product/${productId}/distribution`,
      SEARCH_REVIEWS: '/reviews/search',
      MARK_AS_HELPFUL: (reviewId: number) => `/reviews/${reviewId}/helpful`,
      MARK_AS_UNHELPFUL: (reviewId: number) => `/reviews/${reviewId}/unhelpful`,
      REMOVE_HELPFUL_MARK: (reviewId: number) => `/reviews/${reviewId}/helpful`,
      REPORT_REVIEW: (reviewId: number) => `/reviews/${reviewId}/report`,
      VERIFY_REVIEW: (reviewId: number) => `/reviews/${reviewId}/verify`,
      APPROVE_REVIEW: (reviewId: number) => `/reviews/${reviewId}/approve`,
      REJECT_REVIEW: (reviewId: number) => `/reviews/${reviewId}/reject`,
      GET_PENDING_REVIEWS: '/reviews/pending',
      GET_STATISTICS: '/reviews/statistics',
      GET_TOP_RATED_PRODUCTS: '/reviews/top-rated-products',
      GET_LOWEST_RATED_PRODUCTS: '/reviews/lowest-rated-products',
      GET_RECENT_REVIEWS: '/reviews/recent',
      EXPORT_REVIEWS: '/reviews/export',
      CREATE_PRODUCT_REVIEW: '/reviews/product',
      CREATE_VENDOR_REVIEW: '/reviews/vendor',
      GET_PRODUCT_REVIEWS: (productId: number) => `/reviews/product/${productId}`,
      GET_VENDOR_REVIEWS: (vendorId: number) => `/reviews/vendor/${vendorId}`,
    },

    // ===== WISHLIST =====
    WISHLIST: {
      GET_WISHLIST: '/wishlist',
      GET_WISHLIST_ITEMS: '/wishlist/items',
      ADD_TO_WISHLIST: '/wishlist',
      CLEAR_WISHLIST: '/wishlist/clear',
      GET_WISHLIST_COUNT: '/wishlist/count',
      MOVE_TO_CART: (productId: number) => `/wishlist/${productId}/move-to-cart`,
      SHARE_WISHLIST: '/wishlist/share',
      CREATE_PUBLIC_WISHLIST: '/wishlist/public',
      GET_PUBLIC_WISHLISTS: '/wishlist/public',
      GET_WISHLIST_BY_CODE: (code: string) => `/wishlist/public/${code}`,
      SEARCH_WISHLISTS: '/wishlist/search',
      GET_STATISTICS: '/wishlist/statistics',
      GET_MOST_WISHED_PRODUCTS: '/wishlist/most-wished',
      GET_TRENDING_WISHED_PRODUCTS: '/wishlist/trending',
      ADD_MULTIPLE_TO_WISHLIST: '/wishlist/bulk',
      EXPORT_WISHLIST: '/wishlist/export',
      ADD_TO_WISHLIST_OLD: (productId: number) => `/wishlist/add/${productId}`,
      ADD_TO_WISHLIST_DIRECT: '/wishlist',
      GET_MY_WISHLIST: '/wishlist/my-wishlist',
      GET_USER_WISHLIST: (userId: number) => `/wishlist/user/${userId}`,
      REMOVE_FROM_WISHLIST: (productId: number) => `/wishlist/remove/${productId}`,
      REMOVE_FROM_WISHLIST_BY_ID: (id: number) => `/wishlist/${id}`,
      CHECK_IN_WISHLIST: (productId: number) => `/wishlist/check/${productId}`,
    },

    // ===== PAYMENTS =====
    PAYMENTS: {
      GET_PAYMENT_METHODS: '/payments/methods',
      GET_PAYMENT_METHOD_BY_ID: (id: number) => `/payments/methods/${id}`,
      ADD_PAYMENT_METHOD: '/payments/methods',
      UPDATE_PAYMENT_METHOD: (id: number) => `/payments/methods/${id}`,
      DELETE_PAYMENT_METHOD: (id: number) => `/payments/methods/${id}`,
      SET_DEFAULT_PAYMENT_METHOD: (id: number) => `/payments/methods/${id}/default`,
      CREATE_PAYMENT: '/payments',
      GET_PAYMENT_BY_ID: (id: number) => `/payments/${id}`,
      GET_ORDER_PAYMENTS: (orderId: number) => `/payments/order/${orderId}`,
      GET_ALL_PAYMENTS: '/payments',
      GET_BY_STATUS: (status: string) => `/payments/status/${status}`,
      PROCESS_PAYMENT: (paymentId: number) => `/payments/${paymentId}/process`,
      VERIFY_PAYMENT: '/payments/verify',
      CONFIRM_PAYMENT: (paymentId: number) => `/payments/${paymentId}/confirm`,
      REFUND_PAYMENT: (paymentId: number) => `/payments/${paymentId}/refund`,
      CANCEL_PAYMENT: (paymentId: number) => `/payments/${paymentId}/cancel`,
      INITIALIZE_STRIPE_PAYMENT: '/payments/stripe/initialize',
      INITIALIZE_PAYPAL_PAYMENT: '/payments/paypal/initialize',
      INITIALIZE_RAZORPAY_PAYMENT: '/payments/razorpay/initialize',
      HANDLE_STRIPE_WEBHOOK: '/payments/stripe/webhook',
      HANDLE_PAYPAL_WEBHOOK: '/payments/paypal/webhook',
      HANDLE_RAZORPAY_WEBHOOK: '/payments/razorpay/webhook',
      GET_TRANSACTION_HISTORY: '/payments/transactions',
      GET_TRANSACTION_DETAILS: (transactionId: string) => `/payments/transactions/${transactionId}`,
      GET_STATISTICS: '/payments/statistics',
      GET_TOTAL_REVENUE: '/payments/revenue/total',
      GET_REVENUE_BY_DATE: '/payments/revenue/by-date',
      GET_PAYMENT_METHOD_STATS: '/payments/statistics/methods',
      GET_SUBSCRIPTION_PLANS: '/payments/subscription-plans',
      GET_VENDOR_PAYMENTS: (vendorId: number) => `/payments/vendor/${vendorId}`,
    },

    // ===== VENDORS =====
    VENDORS: {
      // CRUD
      CREATE_VENDOR: '/v1/vendors',
      GET_VENDOR_BY_ID: (id: number) => `/v1/vendors/${id}`,
      UPDATE_VENDOR: (id: number) => `/v1/vendors/${id}`,
      DELETE_VENDOR: (id: number) => `/v1/vendors/${id}`,
      
      // Listing & Search
      GET_ALL_VENDORS: '/v1/vendors',
      SEARCH_VENDORS: '/v1/vendors/search',
      FILTER_VENDORS: '/v1/vendors/filter',
      
      // Verification & KYC
      VERIFY_VENDOR: '/v1/vendors/verify',
      SUBMIT_KYC: (id: number) => `/v1/vendors/${id}/kyc`,
      GET_PENDING_KYC: '/v1/vendors/kyc/pending',
      GET_PENDING_APPROVAL: '/v1/vendors/approval/pending',
      GET_BY_STATUS: (status: string) => `/v1/vendors/status/${status}`,
      
      // Status Management
      UPDATE_STATUS: (id: number) => `/v1/vendors/${id}/status`,
      ACTIVATE_VENDOR: (id: number) => `/v1/vendors/${id}/activate`,
      DEACTIVATE_VENDOR: (id: number) => `/v1/vendors/${id}/deactivate`,
      SUSPEND_VENDOR: (id: number) => `/v1/vendors/${id}/suspend`,
      
      // Type & Subscription
      GET_BY_BUSINESS_TYPE: (type: string) => `/v1/vendors/type/${type}`,
      UPGRADE_VENDOR: (id: number) => `/v1/vendors/${id}/upgrade`,
      SET_FEATURED: (id: number) => `/v1/vendors/${id}/featured`,
      SET_PRIORITY: (id: number) => `/v1/vendors/${id}/priority`,
      
      // Business Information
      GET_BY_CATEGORY: (category: string) => `/v1/vendors/category/${category}`,
      GET_BY_SERVICE_AREA: (area: string) => `/v1/vendors/service-area/${area}`,
      GET_BY_FEATURE: (feature: string) => `/v1/vendors/feature/${feature}`,
      
      // Performance & Analytics
      GET_TOP_PERFORMING: '/v1/vendors/top-performing',
      GET_BY_RATING: (rating: number) => `/v1/vendors/rating/${rating}`,
      GET_BY_ORDERS: (orders: number) => `/v1/vendors/orders/${orders}`,
      GET_BY_REVENUE: (revenue: number) => `/v1/vendors/revenue/${revenue}`,
      GET_FEATURED_VENDORS: '/v1/vendors/featured',
      GET_CERTIFIED_VENDORS: '/v1/vendors/certified',
      
      // Profile Management
      UPDATE_PROFILE: (id: number) => `/v1/vendors/${id}/profile`,
      UPDATE_IMAGES: (id: number) => `/v1/vendors/${id}/images`,
      UPDATE_CONTACT_PERSON: (id: number) => `/v1/vendors/${id}/contact-person`,
      UPDATE_BUSINESS_INFO: (id: number) => `/v1/vendors/${id}/business-info`,
      UPDATE_SERVICE_AREAS: (id: number) => `/v1/vendors/${id}/service-areas`,
      UPDATE_PAYMENT_METHODS: (id: number) => `/v1/vendors/${id}/payment-methods`,
      UPDATE_CERTIFICATIONS: (id: number) => `/v1/vendors/${id}/certifications`,
      
      // Validation & Lookup
      VALIDATE_EMAIL: (email: string) => `/v1/vendors/validate/email/${email}`,
      VALIDATE_PHONE: (phone: string) => `/v1/vendors/validate/phone/${phone}`,
      VALIDATE_COMPANY: (id: number) => `/v1/vendors/validate/company/${id}`,
      LOOKUP_EMAIL: (email: string) => `/v1/vendors/lookup/email/${email}`,
      LOOKUP_PHONE: (phone: string) => `/v1/vendors/lookup/phone/${phone}`,
      LOOKUP_COMPANY: (id: number) => `/v1/vendors/lookup/company/${id}`,
      
      // Authentication & Password
      AUTHENTICATE: '/v1/vendors/authenticate',
      UPDATE_PASSWORD: (id: number) => `/v1/vendors/${id}/password`,
      
      // Statistics
      GET_STATISTICS: '/v1/vendors/statistics',
      GET_TOTAL_COUNT: '/v1/vendors/statistics/count',
      GET_ACTIVE_COUNT: '/v1/vendors/statistics/active',
      GET_VERIFIED_COUNT: '/v1/vendors/statistics/verified',
      GET_KYC_APPROVED_COUNT: '/v1/vendors/statistics/kyc-approved',
      GET_FEATURED_COUNT: '/v1/vendors/statistics/featured',
      GET_AVERAGE_RATING: '/v1/vendors/statistics/average-rating',
      GET_TOTAL_REVENUE: '/v1/vendors/statistics/total-revenue',
      GET_TOTAL_ORDERS: '/v1/vendors/statistics/total-orders',
      
      // Recent
      GET_RECENT_VENDORS: '/v1/vendors/recent',
    },

    // ===== ADMIN LEADS =====
    LEADS: {
      CREATE_LEAD: '/leads',
      GET_LEAD_BY_ID: (id: number) => `/leads/${id}`,
      GET_LEADS_BY_VENDOR: (vendorId: number) => `/leads/vendor/${vendorId}`,
      GET_LEADS_BY_STATUS: (vendorId: number, status: string) => `/leads/vendor/${vendorId}/status/${status}`,
      GET_LEADS_BY_PRIORITY: (vendorId: number, priority: string) => `/leads/vendor/${vendorId}/priority/${priority}`,
      UPDATE_LEAD: (id: number) => `/leads/${id}`,
      UPDATE_LEAD_STATUS: (id: number) => `/leads/${id}/status`,
      UPDATE_LEAD_PRIORITY: (id: number) => `/leads/${id}/priority`,
      ADD_NOTES: (id: number) => `/leads/${id}/notes`,
      DELETE_LEAD: (id: number) => `/leads/${id}`,
      GET_OVERDUE_FOLLOWUPS: (vendorId: number) => `/leads/vendor/${vendorId}/overdue`,
      GET_RECENT_LEADS: (vendorId: number) => `/leads/vendor/${vendorId}/recent`,
      GET_LEAD_STATS: (vendorId: number) => `/leads/vendor/${vendorId}/stats`,
      SEARCH_LEADS: (vendorId: number) => `/leads/vendor/${vendorId}/search`,
      FIND_DUPLICATES: '/leads/duplicates',
      GET_STATUSES: '/leads/statuses',
      GET_PRIORITIES: '/leads/priorities',
    },

    // ===== FILE UPLOAD =====
    FILES: {
      UPLOAD_FILE: '/files/upload',
      UPLOAD_MULTIPLE: '/files/upload/multiple',
      DELETE_FILE: '/files/delete',
    },

    // ===== SUPPORT TICKETS =====
    SUPPORT: {
      CREATE_TICKET: '/support-tickets',
      GET_TICKETS: '/support-tickets',
      GET_TICKET_BY_ID: (id: number) => `/support-tickets/${id}`,
      UPDATE_TICKET: (id: number) => `/support-tickets/${id}`,
      UPDATE_TICKET_STATUS: (id: number) => `/support-tickets/${id}/status`,
      GET_TICKET_STATS: '/support-tickets/stats',
    },

    // ===== CATEGORIES =====
    CATEGORIES: {
      GET_ALL_CATEGORIES: '/categories',
      GET_CATEGORY_BY_ID: (id: number) => `/categories/${id}`,
      GET_CATEGORY_BY_SLUG: (slug: string) => `/categories/slug/${slug}`,
      CREATE_CATEGORY: '/categories',
      UPDATE_CATEGORY: (id: number) => `/categories/${id}`,
      DELETE_CATEGORY: (id: number) => `/categories/${id}`,
      GET_ACTIVE_CATEGORIES: '/categories/active',
      GET_CATEGORIES_WITH_PRODUCTS: '/categories/with-products',
      GET_PARENT_CATEGORIES: '/categories/parent',
      GET_SUBCATEGORIES: (parentId: number) => `/categories/${parentId}/subcategories`,
      GET_CATEGORY_TREE: '/categories/tree',
      GET_CATEGORY_HIERARCHY: '/categories/hierarchy',
      GET_CATEGORY_PRODUCTS: (id: number) => `/categories/${id}/products`,
      SEARCH_CATEGORIES: '/categories/search',
      FILTER_CATEGORIES: '/categories/filter',
      GET_STATISTICS: '/categories/statistics',
      GET_TOTAL_COUNT: '/categories/count',
      GET_TRENDING_CATEGORIES: '/categories/trending',
      GET_TOP_CATEGORIES: '/categories/top',
      REORDER_CATEGORIES: '/categories/reorder',
      BULK_UPDATE_CATEGORIES: '/categories/bulk-update',
      BULK_ACTIVATE_CATEGORIES: '/categories/bulk-activate',
      BULK_DEACTIVATE_CATEGORIES: '/categories/bulk-deactivate',
      BULK_DELETE_CATEGORIES: '/categories/bulk-delete',
      EXPORT_CATEGORIES: '/categories/export',
      IMPORT_CATEGORIES: '/categories/import',
    },

    // ===== NOTIFICATIONS =====
    NOTIFICATIONS: {
      GET_NOTIFICATIONS: '/notifications',
      GET_NOTIFICATION_BY_ID: (id: number) => `/notifications/${id}`,
      GET_UNREAD_NOTIFICATIONS: '/notifications/unread',
      GET_NOTIFICATION_COUNT: '/notifications/count',
      MARK_AS_READ: (id: number) => `/notifications/${id}/read`,
      MARK_AS_UNREAD: (id: number) => `/notifications/${id}/unread`,
      MARK_ALL_AS_READ: '/notifications/mark-all-read',
      DELETE_NOTIFICATION: (id: number) => `/notifications/${id}`,
      DELETE_ALL_NOTIFICATIONS: '/notifications/delete-all',
      GET_UNREAD_COUNT: '/notifications/unread-count',
      GET_PREFERENCES: '/notifications/preferences',
      UPDATE_PREFERENCES: '/notifications/preferences',
      ARCHIVE_NOTIFICATION: (id: number) => `/notifications/${id}/archive`,
      GET_ARCHIVED_NOTIFICATIONS: '/notifications/archived',
      GET_BY_TYPE: (type: string) => `/notifications/type/${type}`,
      SEARCH_NOTIFICATIONS: '/notifications/search',
      TEST_NOTIFICATION: '/notifications/test',
      SUBSCRIBE_TO_TOPIC: '/notifications/subscribe',
      UNSUBSCRIBE_FROM_TOPIC: '/notifications/unsubscribe',
      GET_SUBSCRIBED_TOPICS: '/notifications/topics',
      REGISTER_PUSH_TOKEN: '/notifications/push-token/register',
      UNREGISTER_PUSH_TOKEN: '/notifications/push-token/unregister',
      GET_STATISTICS: '/notifications/statistics',
      GET_RECENT_NOTIFICATIONS: '/notifications/recent',
      EXPORT_NOTIFICATIONS: '/notifications/export',
    },

    // ===== COUPONS =====
    COUPONS: {
      CREATE_COUPON: '/coupons',
      GET_ALL_COUPONS: '/coupons',
      GET_COUPON_BY_ID: (id: number) => `/coupons/${id}`,
      GET_COUPON_BY_CODE: (code: string) => `/coupons/code/${code}`,
      UPDATE_COUPON: (id: number) => `/coupons/${id}`,
      DELETE_COUPON: (id: number) => `/coupons/${id}`,
      VALIDATE_COUPON: '/coupons/validate',
      GET_ACTIVE_COUPONS: '/coupons/active',
      GET_EXPIRED_COUPONS: '/coupons/expired',
      GET_BY_STATUS: (status: string) => `/coupons/status/${status}`,
      GET_MY_COUPONS: '/coupons/my-coupons',
      APPLY_COUPON: '/coupons/apply',
      REMOVE_COUPON: '/coupons/remove',
      REDEEM_COUPON: '/coupons/redeem',
      GET_COUPON_USAGE: (id: number) => `/coupons/${id}/usage`,
      SEARCH_COUPONS: '/coupons/search',
      FILTER_COUPONS: '/coupons/filter',
      GET_STATISTICS: '/coupons/statistics',
      GET_TOTAL_COUNT: '/coupons/count',
      GET_TOP_COUPONS: '/coupons/top',
      GET_MOST_USED_COUPONS: '/coupons/most-used',
      GET_TOTAL_SAVINGS: '/coupons/total-savings',
      GET_SAVINGS_BY_DATE_RANGE: '/coupons/savings-range',
      BULK_CREATE_COUPONS: '/coupons/bulk-create',
      BULK_UPDATE_COUPONS: '/coupons/bulk-update',
      BULK_ACTIVATE_COUPONS: '/coupons/bulk-activate',
      BULK_DEACTIVATE_COUPONS: '/coupons/bulk-deactivate',
      BULK_DELETE_COUPONS: '/coupons/bulk-delete',
      EXPORT_COUPONS: '/coupons/export',
      IMPORT_COUPONS: '/coupons/import',
    },

    // ===== SEARCH =====
    SEARCH: {
      SEARCH: '/search',
      SEARCH_PRODUCTS: '/search/products',
      SEARCH_CATEGORIES: '/search/categories',
      SEARCH_VENDORS: '/search/vendors',
      SEARCH_BLOGS: '/search/blogs',
      GET_SEARCH_SUGGESTIONS: '/search/suggestions',
      GET_SEARCH_HISTORY: '/search/history',
      CLEAR_SEARCH_HISTORY: '/search/history',
      GET_SAVED_SEARCHES: '/search/saved',
      SAVE_SEARCH: '/search/saved',
      REMOVE_SAVED_SEARCH: (searchId: number) => `/search/saved/${searchId}`,
      GET_TRENDING_SEARCHES: '/search/trending',
      GET_TRENDING_PRODUCTS: '/search/trending/products',
      GET_RELATED_SEARCHES: '/search/related',
      GET_RELATED_PRODUCTS: '/search/related/products',
      ADVANCED_SEARCH: '/search/advanced',
      FILTER_PRODUCTS: '/search/filter',
      GET_AVAILABLE_FILTERS: '/search/filters',
      GET_PRICE_RANGE: '/search/price-range',
      GET_CATEGORIES: '/search/categories/list',
      GET_VENDORS: '/search/vendors/list',
      GET_RATINGS: '/search/ratings',
      GET_SORT_OPTIONS: '/search/sort-options',
      TRACK_SEARCH_ANALYTICS: '/search/analytics/track',
      GET_SEARCH_ANALYTICS: '/search/analytics',
      GET_ZERO_RESULTS_SEARCHES: '/search/analytics/zero-results',
      EXPORT_SEARCH_RESULTS: '/search/export',
    },

    // ===== ANALYTICS =====
    ANALYTICS: {
      GET_DASHBOARD_DATA: '/analytics/dashboard',
      GET_SALES_DATA: '/analytics/sales',
      GET_REVENUE_DATA: '/analytics/revenue',
      GET_TOP_PRODUCTS: '/analytics/top-products',
      GET_TOP_CATEGORIES: '/analytics/top-categories',
      GET_TOP_VENDORS: '/analytics/top-vendors',
      GET_CUSTOMER_DATA: '/analytics/customers',
      GET_NEW_CUSTOMERS: '/analytics/new-customers',
      GET_CUSTOMER_RETENTION: '/analytics/customer-retention',
      GET_ORDER_DATA: '/analytics/orders',
      GET_ORDER_STATUS: '/analytics/order-status',
      GET_AVERAGE_ORDER_VALUE: '/analytics/average-order-value',
      GET_CONVERSION_RATE: '/analytics/conversion-rate',
      GET_TRAFFIC_DATA: '/analytics/traffic',
      GET_SEARCH_ANALYTICS: '/analytics/search',
      GET_INVENTORY_ANALYTICS: '/analytics/inventory',
      GET_PAYMENT_METHOD_STATS: '/analytics/payment-methods',
      GET_SHIPPING_DATA: '/analytics/shipping',
      GET_RETURN_DATA: '/analytics/returns',
      GET_REFUND_DATA: '/analytics/refunds',
      GET_MARKETING_DATA: '/analytics/marketing',
      GET_COUPON_USAGE_DATA: '/analytics/coupon-usage',
      GET_CUSTOM_REPORT: '/analytics/custom-report',
      EXPORT_REPORT: '/analytics/export',
      SCHEDULE_REPORT: '/analytics/schedule-report',
      GET_SCHEDULED_REPORTS: '/analytics/scheduled-reports',
      DELETE_SCHEDULED_REPORT: (reportId: number) => `/analytics/scheduled-reports/${reportId}`,
    },
  },

  // Headers configuration
  HEADERS: {
    CONTENT_TYPE_JSON: { 'Content-Type': 'application/json' },
    CONTENT_TYPE_FORM: { 'Content-Type': 'multipart/form-data' },
  },
};

export default API_CONFIG;
